### ISSUE TITLE
[request] modrinth 1.19.2 forge release

### ISSUE THREAD

**Issue by Yarden-zamir** [MinecraftFreecam/Freecam#120]
Currently it seems missing, would be great if we could have a release there

**Comment by Yarden-zamir** [comment]
@hashalite you have it released on forge so I assume it shouldn't be an issue

**Comment by Yarden-zamir** [comment]
If it is an issue, your license allows redistribution but i'll ask anyway, is it alright if we upload a forge dist of your mod to modrinth?

**Comment by hashalite** [comment]
I could post a one-time build sometime soon-ish, 1.19.2 won't be actively supported, though.

**Comment by Yarden-zamir** [comment]
That would work, thank you

**Comment by Yarden-zamir** [comment]
(smi polite ping)

**Comment by MattSturgeon** [comment]
Here's an [unofficial build](https://github.com/MinecraftFreecam/Freecam/files/13868497/freecam-1.2.2%2B1.19.2.zip) you can test out if you like. Built using [this branch](https://github.com/MattSturgeon/Freecam/commits/1.19.2/).

Report any issues in this thread, as I've not tested it much.

Not sure if @hashalite plans to make an official 1.19.2 release or not?

**Comment by hashalite** [comment]
Yes, it is planned, just not the highest priority right now

> Not sure if @hashalite plans to make an official 1.19.2 release or not?

**Comment by Yarden-zamir** [comment]
> Here's an [unofficial build](https://github.com/MinecraftFreecam/Freecam/files/13868497/freecam-1.2.2%2B1.19.2.zip) you can test out if you like.
> 
> Report any issues in this thread, as I've not tested it much.
> 
> Not sure if @hashalite plans to make an official 1.19.2 release or not? If so he can build off of [this branch](https://github.com/MattSturgeon/Freecam/commits/1.19.2/).

Ah thank you. Can you upload the jar as a part of a github release? That way we can include it in modrinth packs before it gets on the platform

**Comment by hashalite** [comment]
Freecam 1.2.3 for 1.19.2 is now available (https://modrinth.com/mod/freecam/version/tXR5Jx3F)
