### ISSUE TITLE
Gradle publishing

### ISSUE THREAD

**Issue by MattSturgeon** [MinecraftFreecam/Freecam#134]
[This plugin](https://github.com/firstdarkdev/modpublisher) aims to simplify publishing artifacts to GitHub releases, curseforge & modrinth.

Once set up, publishing a release would be done by running a gradle publish task. The secret keys for each platform would need to be set as environment variables (or similar).

The plugin author has [added](https://github.com/firstdarkdev/modpublisher/issues/3) the ability to override the artifact for a specific platform, meaning we can upload the restricted build to modrinth.

There are alternative plugins that do similar things. E.g. shedanial maintains [`unified-publishing`](https://github.com/shedaniel/unified-publishing), ~~which I haven't looked into yet~~. _EDIT: looks equally straightforward, perhaps a bit more fleshed out._

You can also use the various APIs manually, however a plugin centralised a lot of shared configuration and streamlines the process.

**Comment by hashalite** [comment]
Looks like something that could save a lot of time - will definitely have to look into this
