### ISSUE TITLE
Cannot access config

### ISSUE THREAD

**Issue by Chopperwhitewolf** [MinecraftFreecam/Freecam#159]
I am using Freecam-Fabric-1.2.1+1.20.jar with Curseforge
My issue is I have been unable to access the setting menu to adjust camera speed, control player and other assorted settings. I have tried to go in through the game menu, through Curseforge, through the Mod folder and with no success.

Please advise

**Comment by MattSturgeon** [comment]
First, make sure you have ModMenu installed.

Then go to menu -> Mods -> Freecam -> <img style="max-height: 1em;vertical-align: middle; " alt="🛠️" src="https://github.com/MinecraftFreecam/Freecam/assets/5046562/abe13343-2b97-4035-b96d-dfaddd19adc6">
