### ISSUE TITLE
Freecam 1.2.2 (MC 1.20.4) missing from Modrinth

### ISSUE THREAD

**Issue by masterflitzer** [MinecraftFreecam/Freecam#161]
Freecam 1.2.2 (MC 1.20.4) is not available on Modrinth: https://modrinth.com/mod/freecam/versions

**Comment by MattSturgeon** [comment]
Closing this as 1.2.2 probably won't get fully published everywhere.

We've been working on improving our release process, so @hashalite is planning to make a new release soon on all supported platforms using the new systems.

Hopefully there won't be too long to wait.

**Comment by MattSturgeon** [comment]
FYI: Freecam 1.2.3 is now [available on Modrinth](https://modrinth.com/mod/freecam/versions?g=1.20.4), as well as [GitHub](https://github.com/MinecraftFreecam/Freecam/releases/tag/1.2.3) and [Curseforge](https://www.curseforge.com/minecraft/mc-mods/free-cam/files/all?page=1&pageSize=20&version=1.20.4).

**Comment by masterflitzer** [comment]
thank you for the info :)
