### ISSUE TITLE
Use this code for a security camera mod.

### ISSUE THREAD

**Issue by PaulRVIFS** [MinecraftFreecam/Freecam#176]
Hey there, do you allow people to use this mod's code for other mods? I want to create a security camera mod for fabric, like Security Craft on forge, and this is the best baseline I have found, since I would just need to lock the player camera to different positions.

**Comment by MattSturgeon** [comment]
The code is [MIT licensed](https://github.com/MinecraftFreecam/Freecam/blob/main/LICENSE), so you can use it **however you like**. The main restriction is that you need to include the copyright notice & license text along with any redistribution. [This page summarizes the MIT license](https://www.tldrlegal.com/license/mit-license) quite well.
