### ISSUE TITLE
Camera Movement Options

### ISSUE THREAD

**Issue by Xisuma** [MinecraftFreecam/Freecam#181]
Suggestion : Add an option to have the free cam movement like that of spectator?
You could also add other options like speed/sensitivity too :-)

Thanks!

**Comment by MattSturgeon** [comment]
Thanks for taking the time to suggest this idea!

Just to clarify, would "spectator" style movement be different from the existing "creative" style movement option? If not, maybe we should consider a better name...

There's also basic speed settings too, although there's some related suggestions (#48 and #158), which I'm definitely interested in implementing when I get chance to think about the best approach.
