### ISSUE TITLE
[New Language]: Toki Pona

### ISSUE THREAD

**Issue by PiggyDr** [MinecraftFreecam/Freecam#197]
### Language name

Toki Pona

### Locale code

tok

### Please check if the language is already enabled

- [X] I have checked this language isn't enabled on Crowdin

**Comment by MattSturgeon** [comment]
I don't mean to sound dismissive, but what is the motivation for this? Will this benefit any users? If so, how?

**Comment by PiggyDr** [comment]
this is just what tokiponists do in their free time

the Minecraft Toki Pona localization is mainly used for learning purposes to my knowledge, and Freecam is definitely popular enough that people will be able to get utility out of it. whether or not a significant amount of people will get utility out of it is debatable tho and actual usage is definitely a valid concern

(sorry for the late response)

**Comment by MattSturgeon** [comment]
I've given this some thought and I don't think we'll add support. I just don't think the maintenance burden will be worth it for us.

Keep in mind that it is still possible to create third party localisation resource packs, so you could still do this independently if desired.
