### ISSUE TITLE
[1.21- Modrinth edition] "Cheats" seem to still be on even on a server, not opped and not in creative

### ISSUE THREAD

**Issue by jinkhya** [MinecraftFreecam/Freecam#227]
### Description of the issue

Hello again ! 
There seems to be an issue with the modrinth edition. I setup a vanilla server with no modloader or any plugins. Joined with my client ( I'm not opped) with fabric+modrinth edition and I can use it underground.

Thanks in advance,
Jin

### Expected behavior

to not work underground with modrinth edition :)

### Steps to reproduce

1. setup a vanilla server
2. join with client with fabric +modrinthFreecam
3. toggle freecam
4. go underground

### Freecam version

freecam-fabric-1.3.0-beta1+mc1.21

### Are you using "Modrinth Edition"?

Yes

### Minecraft version

1.21

### Modding platform

- [X] Fabric
- [ ] Neoforge
- [ ] Forge

**Comment by jinkhya** [comment]
So it looks like this may be an easy fix. The uploaded 1.21 version on Modrinth is not the modrinth version :)

**Comment by hashalite** [comment]
My fault, I should have double checked. Will get that fixed ASAP

**Comment by hashalite** [comment]
Fixed now, sorry about that!
