### ISSUE TITLE
I can't move blocks

### ISSUE THREAD

**Issue by Matxix65** [MinecraftFreecam/Freecam#231]
### Description of the issue

I can't get past the blocks and I can't find a way to activate the no-clip

### Steps to reproduce

1. Open a singleplayer world
2. Enable Freecam by pressing `F4`
3. ...

### How prevalent is the issue?

Every time I try to occupy it

### Freecam version

1.2.1

### Are you using "Modrinth Edition"?

Yes

### Minecraft version

1.20.1

### Modding platform

- [X] Fabric
- [ ] Neoforge
- [ ] Forge

**Comment by Matxix65** [comment]
Sorry if it's written wrong, I speak Spanish and I had to use the translator (I didn't see anyone use Spanish)

**Comment by MattSturgeon** [comment]
Thanks for reporting your issues!

This is a Modrinth Edition restriction.

Due to Modrinth's anti-chrating policies, Freecam's collision settings are restricted to singleplayer and servers where you are op.

You can download Freecam from GitHub or CurseForge instead.
