### ISSUE TITLE
Provide support for 1.21.3

### ISSUE THREAD

**Issue by Chromeyyy** [MinecraftFreecam/Freecam#254]
### Description of the feature

As the title says, can you please add support for 1.21.3 as this mod is very useful? Latest version of 1.21 doesn't work and crashes the game.

### Freecam version

Unrelated

**Comment by MattSturgeon** [comment]
This was (just) resolved in https://github.com/MinecraftFreecam/Freecam/pull/252.

You can use the [CI build artifacts](https://github.com/MinecraftFreecam/Freecam/actions/runs/11644373566#artifacts) while you wait for a release to be published.

Any pre-release feedback would also be greatly appreciated (as always)!

**Comment by Chromeyyy** [comment]
Awesome.

**Comment by MattSturgeon** [comment]
FYI 1.21.3 support has made it into a new free cam release, [1.3.1](https://github.com/MinecraftFreecam/Freecam/releases/tag/v1.3.1). Also available on curseforge and modrinth.
